///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AreaMap {
/*
{
  "id": 1,
  "name": "鎮守府海域",
  "maps": [
    11
  ],
  "event": false
} 
*/

  int id;
  String name;
  List<int> maps;
  bool event;

  AreaMap({
    this.id,
    this.name,
    this.maps,
    this.event,
  });
  AreaMap.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
  if (json['maps'] != null) {
  final v = json['maps'];
  final arr0 = <int>[];
  v.forEach((v) {
  arr0.add(v.toInt());
  });
    maps = arr0;
    }
    event = json['event'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    if (maps != null) {
      final v = maps;
      final arr0 = [];
  v.forEach((v) {
  arr0.add(v);
  });
      data['maps'] = arr0;
    }
    data['event'] = event;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class KcdataMap {
/*
{
  "id": 11,
  "name": "鎮守府正面海域"
} 
*/

  int id;
  String name;

  KcdataMap({
    this.id,
    this.name,
  });
  KcdataMap.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}
